modLoader="javafml"
loaderVersion="[47,)"
license="Attribution-NonCommercial-ShareAlike 4.0 International"
[[mods]]
modId="dglib"
version="1.1_alpha"
displayName="DGLib"
authors="msdoggirl"
description='''
  Common code for MsDogGirl's mods. Includes dynamic skin swapping and emissive skin layer APIs. 
  '''
[[dependencies.dglib]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"
[[mixins]]
config="mixins.dglib.json"

